<fieldset class="fieldset create account" data-hasrequired="<?php echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php echo __('Additional Information') ?></span></legend>
    <div class="field my_attribute required">
        <label for="linkedin_profile" class="label"><span><?php echo __('Linkedin Profile URL') ?></span></label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile" value="<?php echo $block->getCustomer()->getCustomAttribute('linkedin_profile')->getValue(); ?>" title="<?php echo __('Linkedin Profile URL') ?>" class="input-text" data-validate="{required:true, 'validate-url':true, maxlength:250}" autocomplete="off">
        </div>
    </div>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$config =  $objectManager->create('\Magento\Framework\App\Config\ScopeConfigInterface');
echo $config->getValue('customer_attribute/customer_attribute_validation/linkedin_profile_validation');
?>
</fieldset>
