<fieldset class="fieldset create account" data-hasrequired="<?php echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php echo __('Additional Information') ?></span></legend>
    <div class="field my_attribute required">
        <label for="linkedin_profile" class="label"><span><?php echo __('Linkedin Profile URL') ?></span></label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile" title="<?php echo __('Linkedin Profile URL') ?>" class="input-text" data-validate="{required:true, 'validate-url':true, maxlength:250}" autocomplete="off">
        </div>
    </div>
</fieldset>
